<?php

namespace Chronos\ChronoAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ChronoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChronoRepository extends EntityRepository
{
    public function getOrderedChrono()
    {
        return $query = $this->createQueryBuilder('ch')
            ->leftJoin('ch.circuit', 'ci')
            ->orderby('ch.asso DESC')
            ->orderby('ch.circuit')
            ->orderBy('ci.country')
            ->getQuery()
            ->getResult();
    }

    public function getAllChronos()
    {
        return $this->createQueryBuilder('e')
            ->getQuery();
    }
}


