<?php

namespace Chronos\ChronoAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CircuitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircuitRepository extends EntityRepository
{
    public function getAllCircuit()
    {
        return $this->createQueryBuilder('e')
            ->getQuery();
    }
}
