ChronosChronoUserBundle:
    resource: "@ChronosChronoUserBundle/Resources/config/routing.yml"
    prefix:   /

ChronosChronoAdminBundle:
    resource: "@ChronosChronoAdminBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
