usr_chrono:
    pattern:  /
    defaults: { _controller: "ChronosChronoUserBundle:Chrono:indexFrench" }

usr_chrono_other:
    pattern:  /other
    defaults: { _controller: "ChronosChronoUserBundle:Chrono:indexOther" }

usr_chrono_show:
    pattern:  /{id}/show
    defaults: { _controller: "ChronosChronoUserBundle:Chrono:show" }



