homepage:
    pattern:  /
    defaults: { _controller: ChronosChronoAdminBundle:Main:index }

ChronosChronoAdminBundle_circuit:
    resource: "@ChronosChronoAdminBundle/Resources/config/routing/circuit.yml"
    prefix:   /circuit

ChronosChronoAdminBundle_chrono:
    resource: "@ChronosChronoAdminBundle/Resources/config/routing/chrono.yml"
    prefix:   /chrono

ChronosChronoAdminBundle_weather:
    resource: "@ChronosChronoAdminBundle/Resources/config/routing/weather.yml"
    prefix:   /weather

ChronosChronoAdminBundle_roadstate:
    resource: "@ChronosChronoAdminBundle/Resources/config/routing/roadstate.yml"
    prefix:   /roadstate