parameters:
#    chronos_chrono_admin.example.class: Chronos\ChronoAdminBundle\Example

services:
#    chronos_chrono_admin.example:
#        class: %chronos_chrono_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
